aks_cluster_name_env =  "aks-cluster-tf-sample"
res_location_env =  "East US"
res_grp_name_env = "DevOps-training" #Resource Group Name
node_count_env = 2
max_count_env = 4
min_count_env = 1
max_pods_env = 45
node_vm_size_env = "Standard_D2s_v3"
envi = "qa"